# Generated by Django 3.1.3 on 2020-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('hire_date', models.DateField(verbose_name='date hire_date')),
                ('fire_date', models.DateField(null=True, verbose_name='date fire_date')),
                ('salary', models.IntegerField()),
                ('fraction', models.IntegerField()),
                ('base', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('by_hours', models.BooleanField()),
            ],
        ),
    ]
