# Generated by Django 3.1.3 on 2020-11-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='fire_date',
            field=models.DateField(blank=True, null=True, verbose_name='date fire_date'),
        ),
    ]
