# Generated by Django 3.1.3 on 2020-11-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201107_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='company_name',
            new_name='companyName',
        ),
    ]
